language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - PANDAS_VERSION="pandas>=0.18,<0.19"
  - PANDAS_VERSION="pandas"

before_script:
  - pip install nose
  - pip install nose-parameterized
  - pip install codecov

# install matrix versions, deps and optional deps
install:
  - pip install -q $PANDAS_VERSION
  - pip install numpy scipy scikit-learn six jellyfish
  - pip install requests

# run tests with coverage
script: nosetests --with-coverage --cover-package=recordlinkage

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)